# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmIndex < Formula
  desc "Index and resume LLM sessions across OpenCode, Zed, and Codex CLI"
  homepage "https://github.com/panchagnula-krishnacharan/llm-index"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/panchagnula-krishnacharan/llm-index/releases/download/v0.1.1/llm-index_0.1.1_darwin_amd64.tar.gz"
      sha256 "03e5ab7b611b56d1a86c368ccbb336e757a6bb5750d90b319849cd959bee988f"

      define_method(:install) do
        bin.install "llm-index"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/panchagnula-krishnacharan/llm-index/releases/download/v0.1.1/llm-index_0.1.1_darwin_arm64.tar.gz"
      sha256 "b51215d145b265f7f4e9d1eb35ad34db3274000ed07d521c030b559d23af0850"

      define_method(:install) do
        bin.install "llm-index"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/panchagnula-krishnacharan/llm-index/releases/download/v0.1.1/llm-index_0.1.1_linux_amd64.tar.gz"
      sha256 "2dfbcb549b2637bba8f6563c43d1789cc6e6564607864204b3350a314ae50f6d"
      define_method(:install) do
        bin.install "llm-index"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/panchagnula-krishnacharan/llm-index/releases/download/v0.1.1/llm-index_0.1.1_linux_arm64.tar.gz"
      sha256 "81ad09b43e9a520ebcee51220c6664ef5a5606260007c92264102c2adb58e0f4"
      define_method(:install) do
        bin.install "llm-index"
      end
    end
  end

  test do
    system "#{bin}/llm-index", "--help"
  end
end
